[install]
exact = false
lockfile = true
frozenLockfile = false
minimumReleaseAge = 259200
minimumReleaseAgeExcludes = ["@types/bun", "@types/node", "typescript"]

[install.scopes]
"@visus-io" = { url = "https://registry.npmjs.org/" }
